#!/bin/bash
md_file=$1
INSTALL_PATH_FOLDER/renderer "$md_file"

# 1. Get Screen Dimensions
SCREEN_WIDTH=$(xdotool getdisplaygeometry | awk '{print $1}')
SCREEN_HEIGHT=$(xdotool getdisplaygeometry | awk '{print $2}')
SCREEN_HEIGHT=$((SCREEN_HEIGHT - 50))
HALF_WIDTH=$((SCREEN_WIDTH / 2))

# 2. Launch feh on the LEFT (Pixels work here)
feh -R 10 --sort filename /tmp/my_screenshots/*.png --geometry "${HALF_WIDTH}x${SCREEN_HEIGHT}+0+0" &

# 3. Launch xterm (Ignore its initial size)
tilix -e vim "$md_file" &

# 4. Give xterm a moment to map the window, then force it to the RIGHT half
sleep 0.5
VIM_WID=$(xdotool search --onlyvisible --class "Tilix" | tail -1)
xdotool windowmove "$VIM_WID" "$HALF_WIDTH" 0
xdotool windowsize "$VIM_WID" "$HALF_WIDTH" "$SCREEN_HEIGHT"
